### ISSUE TITLE
Add backups with Kubernetes CronJobs

### ISSUE THREAD

**Issue by metalmatze** [metalmatze/kube-cockroachdb#1]
On one of my projects I've created a Kubernetes CronJob to automatically backup databases to S3-compatible object storage (with minio).
Going forward this should become a part of kube-cockroachdb.

We need to parameterize a few things, like schedule and secrets, to make it really work for most people.

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cockroachdb-backup
  namespace: app
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cockroachdb
            image: cockroachdb/cockroach:v20.1.0
            command:
            - /bin/bash
            - -ecx
            - exec /cockroach/cockroach dump --url $DSN app > /backups/app.sql
            env:
              - name: DSN
                valueFrom:
                  secretKeyRef:
                    key: DSN
                    name: app
            volumeMounts:
              - name: backups
                mountPath: /backups
          - name: minio
            image: minio/mc:RELEASE.2020-04-04T05-28-55Z
            command:
            - /bin/sh
            - -c
            - sleep 10 && mc cp /backups/app.sql app-$(date +%Y-%m-%d-%H-%M-%S).sql
            env:
              - name: MC_HOST_digitalocean
                value: 'https://XXX@ams3.digitaloceanspaces.com'
            volumeMounts:
              - name: backups
                mountPath: /backups
          volumes:
            - name: backups
              emptyDir: {}
          restartPolicy: OnFailure
```

Please add a reaction to indicate you want this feature and leave a comment for other requirements around this feature.
